### PR TITLE
Revert "Improved type definitions for the maching functions"

### PR DESCRIPTION
**Pull request by NagRock**
Reverts NagRock/ts-mockito#15

### CODE REVIEW

**Comment by NagRock** [comment]
Temporary reverting improved type definitions for matching functions until https://github.com/NagRock/ts-mockito/pull/17 will be ready

**Comment by michalstocki** [comment]
Ok. Are you going to fix the build, to fail on compilation errors in tests?

**Comment by NagRock** [comment]
Yes

**Comment by NagRock** [comment]
@michalstocki now build should fail on typescript errors

**Comment by michalstocki** [comment]
Great!

@michalstocki <https://github.com/michalstocki> now build should fail on

**Pull request merged**
