### PR TITLE
Fix typing

### PR DESCRIPTION
**Pull request by cakeinpanic**
started using new version in my work project and found out that I have to write `objectContaining({data:value}) as any`

fixed this

### CODE REVIEW

**Comment by bendykowski** [comment]
Hi @cakeinpanic, what was the exact problem you had that you needed to remove the returning types of those functions? I don't think this is a good idea. We need to find a better solution for that.

**Comment by cakeinpanic** [comment]
I have added this mathers by myself and obviously made a mistake when set return type to `Matcher` instead of `any`

now i have to write constructions like
`when(myService.getData(objectContaining({id:15} as any).thenReturn(MOCK_RESPONSE)`
otherwise typescript won't compile

**Comment by bendykowski** [comment]
OK, I'll check that when I get home.

**Comment by bendykowski** [comment]
I've checked that again and you are right here. I'm just super sensitive and cautious about casting to any.

**Comment by cakeinpanic** [comment]
@NagRock friendly reminder for review/merge)

**Comment by cakeinpanic** [comment]
@NagRock friendly reminder for review/merge)

**Comment by cakeinpanic** [comment]
@NagRock friendly reminder for review/merge)

**Pull request closed without merging**
