### PR TITLE
Feature fields

### PR DESCRIPTION
**Pull request by smstuebe**
relates to: #23 

see readme additions for explanation.

What do you think?

### CODE REVIEW

**Comment by NagRock** [comment]
I wonder if we can't use current API with `when` method:

```
when(mockedFoo.sampleField).thenReturn("sampleValue");
```

Then we can also use 2.0 API to return multiple values after each call:

```
when(mockedFoo.sampleField).thenReturn("firstValue", "secondValue", "thirdValue");
```

**Comment by NagRock** [comment]
Oh and I forgot, thanks for contributing!

**Comment by smstuebe** [comment]
I thought the same (generate getter and setter), but wasn't sure, if there might be some unintendet egde cases if somebody uses the mock and does some javascript magic.
And what happens, if you set up a sequence, but the consumer calls the setter. which value is returned on the next get?

**Comment by michalstocki** [comment]
I wonder why do we need a special API method for assigning fields to an instance object? This can be easily achieved using the example provided in #23:
```
let inst = instance(fooMock);
inst.isBar = false;
```
First of all, the public fields are rather bad practice in classes containing a logic. If the object doesn't contain any logic, it's a pure data structure and you don't need any mocking mechanism for this. Given that, I would suggest to not add new API method which will support a bad practice.

Moreover mass assignment of object fields is possible without any extra tool:
```
Object.assign(inst, {isBar: true});
```

**Comment by smstuebe** [comment]
> This can be easily achieved using the example provided in #23

Yes you can do that, but than the mock instance is configured with two different approaches.
and
> First of all, the public fields are rather bad practice in classes containing a logic

Yes, but you have three guesses, why I want to to that. Unfortunately, sometimes you have to consume that weird stuff.

**Comment by michalstocki** [comment]
Legacy code? 😛  Feel sorry…

I this case, I would rather create a simple helper fuction in my `test/utils`:
```
function assignProperties<TKey extends keyof T>(mock:T, properties:Pick<T, TKey>) {
  const instance:T = instance(mock);
  Object.assign(instance, properties);
}
```

**Comment by NagRock** [comment]
Thank you both for an interesting discussion, I understand @smstuebe, but more and more feel @michalstocki way.
@smstuebe what do you think about what @michalstocki said?

**Comment by smstuebe** [comment]
@NagRock ofc I could use the helper function. But in #23 I asked if there is a "official" way to do that. If "use this helper function" is the official way, I'm totally fine with it. We can write it down in the readme.md and close the PR. At least the PR triggered the discussion and a decision on how to handle the mocking of fields when using ts-mockito :)

**Comment by NagRock** [comment]
@smstuebe would you like to add info about helper or even into code helper function? I think that @michalstocki is right about mocking fields. How about you?

**Pull request closed without merging**
