### PR TITLE
Allow mocking of defined properties

### PR DESCRIPTION
**Pull request by thomashilzendegen**
These changes should allow mocking of defined properties. Maybe you give it a try?
It also follows the inheritance chain.

Cheers,
Thomas

### CODE REVIEW

**Comment by NagRock** [comment]
Thanks for PR. I will take a look at it and merge if everything is ok.

**Comment by NagRock** [comment]
@thomashilzendegen great job! Thanks for contributing. 👍

**Comment by thomashilzendegen** [comment]
@NagRock You're welcome!

**Comment by NagRock** [comment]
Published as 1.2.0 version on [npm](https://www.npmjs.com/package/ts-mockito)

**Pull request merged**
